---
title: "IMDB analysis"
author: "Josh Faure"
date: "07/12/2020"
output: 
  bookdown::html_document2:
    code_folding: hide
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.path = "plots/", fig.width = 6, fig.height = 5,
                      fig.align = "center", fig.ext = "png", 
                      echo = TRUE, warning = FALSE, message = FALSE, 
                      scipen = 999)
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(ggThemeAssist)
library(cowplot)
library(here)
library(magick)
theme_set(theme_bw())

source("scripts/data_process.R")
```


```{r, include = FALSE}
# process_raw_data() # run only first time, or when any updates occur

files = list.files("clean_data/")
for(i in files){
  fn <- i %>% str_remove_all(".rds")
  assign(fn %>% str_replace_all("[[:punct:]]", "_"), 
         readRDS(paste0("clean_data/", fn, ".rds"))
         ) 
}
```

```{r}
#obtain all tv series information
simpsons <- title_basics %>% dplyr::filter(primary_title == "The Simpsons" & title_type == "tvSeries") %>% 
  dplyr::left_join(title_episode, by = c("tconst"="parent_tconst")) %>% 
  dplyr::left_join(title_ratings, by = c("tconst.y"="tconst")) %>% 
  drop_na() %>% 
  dplyr::transmute(
    tconst, 
    primary_title,
    episode_tconst = `tconst.y`,
    season = parse_number(season_number) %>% factor(),
    episode = parse_number(episode_number), 
    average_rating,
    num_votes
  )

write_csv(simpsons, file = "clean_data/simpsons.csv")

simpsons <- read_csv(file = "clean_data/simpsons.csv")
```

```{r}
# average season rating
lollipop <- simpsons %>% dplyr::transmute(
  season = season %>% factor(),
  episode,
  num_votes,
  total_rating = average_rating * num_votes
  ) %>% group_by(season) %>% 
  summarise(season_rating = sum(total_rating, na.rm = TRUE) / sum(num_votes, na.rm = TRUE)) %>% 
  ggplot(aes(x = season, y = season_rating)) +
  geom_point(aes(colour = season_rating), size = 7) + 
  geom_segment(aes(x = season, xend = season, 
                   y = 0, yend = season_rating,
                   colour = season_rating),
               size = 3) + 
  geom_text(aes(label = round(season_rating, 1)), size = 3, na.rm = TRUE) +
  scale_colour_gradient2_tableau(palette = "Red-Green Diverging") + 
  labs(x = "Season", y = "Average season rating", 
    colour = "Average season rating")


lollipop_blank <- lollipop +   
  theme(panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.border = element_blank(),
    panel.background = element_blank(), 
    plot.background = element_blank(), 
    legend.position = "none") +
  labs(x = NULL, y = NULL, colour = NULL)

# episode x season rating heatmap
heatmap <- simpsons %>% mutate(season = season %>% factor()) %>% 
  ggplot(aes(x = season, y = episode)) +
  geom_tile(aes(fill = average_rating), na.rm = TRUE) +
  geom_text(aes(label = round(average_rating, 1)), size = 3, na.rm = TRUE) +
  scale_fill_gradient2_tableau(palette = "Red-Green Diverging") +
  scale_y_continuous(breaks = 1:25, trans = "reverse") + 
  scale_x_discrete(position = "top") + 
  coord_cartesian(ylim = c(25, 1)) + 
  labs(x = "Season", y = NULL) + 
  theme(panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.border = element_blank(),
    panel.background = element_blank(), 
    plot.background = element_blank(),
    legend.position = "none")
```

```{r}
combined_ratings_plot <- cowplot::plot_grid(lollipop_blank, heatmap, align = "v", ncol = 1, rel_heights = c(0.25, 0.75)) + 
  theme(panel.background = element_rect(fill = "#ffd90f"))

ggsave(combined_ratings_plot, file = "simpsons_decline.png")
```


